"""Promotion to final/ and the SPEC.md bundle.

Fail-closed: existing final/ files are leak-scanned BEFORE anything is
regenerated (hand-edits surface instead of being silently overwritten), and
generated content is scanned before it touches disk. A leak aborts everything.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

from . import mdutil, sources
from .models import GreenhouseError, LeakError

if TYPE_CHECKING:
    from .state import Project

GENERATED_HEADER = "<!-- GENERATED by greenhouse bundle — do not edit; edit workfiles/ and re-run. -->"

_INTERNAL_LINK_RE = re.compile(
    r"\[([^\]]*)\]\((?:\.\./)*(?:sources/|history/references/)[^)]*\)"
)
_GUIDANCE_RE = re.compile(r"<!--\s*guidance:.*?-->\n?", re.DOTALL)


def strip_for_final(text: str) -> str:
    """Remove ref/why markers and scaffold guidance; de-link internal links (text kept).
    Shared by shard promotion and `deliverable write`."""
    text = mdutil.strip_markers(text, why=True, ref=True)
    text = _GUIDANCE_RE.sub("", text)
    text = _INTERNAL_LINK_RE.sub(r"\1", text)
    return text


def _leak_check(content: str, where: str, patterns: list[str]) -> None:
    for pattern in patterns:
        if pattern and pattern in content:
            raise LeakError(
                f"Leak into final/: {pattern!r} found in {where}. "
                "Restate the fact on its own terms; internal material never ships."
            )


def blocking_questions(project: Project) -> list[str]:
    return [
        q.id
        for s in project.spec().sections
        for q in s.open_questions
        if q.blocking
    ]


def promote(project: Project, allow_blocking: bool = False) -> list[str]:
    """Rebuild final/ shards from every agreed/locked section's workfile slice.
    Returns the shard filenames written."""
    spec = project.spec()

    blockers = blocking_questions(project)
    if blockers and not allow_blocking:
        raise GreenhouseError(
            "Blocking questions still open: " + ", ".join(blockers)
            + ". Resolve them or pass --allow-blocking (leaks are never overridable)."
        )

    patterns = sources.leak_patterns(project)

    # step 0 — fail-closed on tampered/hand-edited existing final files,
    # deliverables under final/deliverables/ included
    if project.final_dir.exists():
        for f in sorted(project.final_dir.rglob("*")):
            if not f.is_file():
                continue
            try:
                existing = f.read_text()
            except UnicodeDecodeError:
                continue
            rel = f.relative_to(project.root).as_posix()
            _leak_check(existing, f"{rel} (existing)", patterns)

    # group promotable sections by workfile, in file order
    by_file: dict[str, list] = {}
    for sec in spec.sections:
        if sec.maturity not in ("agreed", "locked") or not sec.workfile:
            continue
        path, _, _anchor = sec.workfile.partition("#")
        by_file.setdefault(path, []).append(sec)

    shards: dict[str, str] = {}
    for path, secs in sorted(by_file.items()):
        fpath = project.root / path
        if not fpath.exists():
            raise GreenhouseError(f"workfile {path} missing")
        text = fpath.read_text()
        headings = mdutil.parse_headings(text)
        h1 = next((h["text"] for h in headings if h["level"] == 1), path)

        def _position(sec: object, text: str = text) -> int:
            anchor = sec.workfile.partition("#")[2]
            for h in mdutil.parse_headings(text):
                if h["slug"] == anchor:
                    return h["line"]
            return 0

        pieces = [f"# {h1}", "", GENERATED_HEADER, ""]
        for sec in sorted(secs, key=_position):
            anchor = sec.workfile.partition("#")[2]
            sliced = mdutil.extract_section_slice(text, anchor) if anchor else text
            if sliced is None:
                raise GreenhouseError(f"{sec.id}: anchor #{anchor} not found in {path}")
            pieces.append(strip_for_final(sliced).rstrip())
            pieces.append("")
        shard_name = fpath.name
        shards[shard_name] = "\n".join(pieces).rstrip() + "\n"

    # step 1 — leak-check generated content before touching disk
    for name, content in shards.items():
        _leak_check(content, f"final/{name} (generated)", patterns)

    project.final_dir.mkdir(parents=True, exist_ok=True)
    for name, content in shards.items():
        (project.final_dir / name).write_text(content)
    return sorted(shards)


def build_spec(project: Project) -> str:
    """Concatenate final/ shards into final/SPEC.md with a TOC. Returns the path."""
    patterns = sources.leak_patterns(project)
    shard_files = [
        f for f in sorted(project.final_dir.glob("*.md")) if f.name != "SPEC.md"
    ]
    if not shard_files:
        raise GreenhouseError("Nothing under final/ to bundle — promote sections first.")

    spec = project.spec()
    toc: list[str] = []
    bodies: list[str] = []
    for f in shard_files:
        text = f.read_text()
        _leak_check(text, f"final/{f.name}", patterns)
        headings = mdutil.parse_headings(text)
        h1 = next((h for h in headings if h["level"] == 1), None)
        if h1:
            toc.append(f"- [{h1['text']}](#{h1['slug']})")
            toc.extend(
                f"  - [{h['text']}](#{h['slug']})"
                for h in headings
                if h["level"] == 2
            )
        bodies.append(re.sub(re.escape(GENERATED_HEADER) + r"\n?", "", text).rstrip())

    content = "\n".join(
        [
            f"# {spec.title or project.name} — Specification",
            "",
            GENERATED_HEADER,
            "",
            f"_{spec.one_liner}_" if spec.one_liner else "",
            "",
            "## Contents",
            "",
            *toc,
            "",
            "---",
            "",
            "\n\n---\n\n".join(bodies),
            "",
        ]
    )
    _leak_check(content, "final/SPEC.md", patterns)
    out = project.final_dir / "SPEC.md"
    out.write_text(content)
    return str(out.relative_to(project.root))


def bundle(project: Project, allow_blocking: bool = False) -> dict[str, object]:
    shards = promote(project, allow_blocking=allow_blocking)
    spec_path = build_spec(project)
    return {"shards": shards, "spec": spec_path}
