"""Deliverables: the artefacts a project expects to receive at finalization,
beyond SPEC.md — an operator guide, an IaC blueprint, a command reference…

Declared per archetype (`deliverables:` in templates/taxonomies/<a>.yaml),
copied into spec-state.yaml at scaffold time so /spec-new re-verifies the
list per project, and fed by named sections. Three consumers:

- drills: `section guidance` lists the deliverables a section feeds and what
  each needs, so the prose carries those facts (without being limited to them);
- coverage: readiness (every feeding section agreed/locked) and staleness
  (a feeding section touched after the file was built);
- finalize: `plan()` hands the finalize skill the inputs per deliverable and
  `write()` lands the AI-written file under final/deliverables/ — markers
  stripped, leak-checked fail-closed, `built_at` stamped.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from . import sources
from .models import Deliverable, GreenhouseError, LeakError, SpecState

if TYPE_CHECKING:
    from pathlib import Path

    from .state import Project

DELIVERABLES_DIR = "deliverables"
INDEX_NAME = "README.md"
INDEX_HEADER = (
    "<!-- GENERATED by greenhouse deliverable write — do not edit; "
    "re-run the finalize deliverable step. -->"
)


def target_path(project: Project, deliverable: Deliverable) -> Path:
    return project.final_dir / DELIVERABLES_DIR / deliverable.filename


def readiness(project: Project, spec: SpecState | None = None) -> list[dict[str, Any]]:
    """One row per deliverable: feeding sections with maturity, what is still
    missing, whether the file exists, and which sections moved after it was
    built (`stale`)."""
    spec = spec or project.spec()
    maturity = {s.id: s for s in spec.sections}
    rows: list[dict[str, Any]] = []
    for d in spec.deliverables:
        feeding = []
        missing = []
        stale = []
        for sid in d.sections:
            sec = maturity.get(spec.canonical_section_id(sid) or sid)
            m = sec.maturity if sec else "?"
            feeding.append({"section": sid, "maturity": m})
            if m not in ("agreed", "locked"):
                missing.append(sid)
            if sec and d.built_at and sec.last_touched and sec.last_touched > d.built_at:
                stale.append(sid)
        path = target_path(project, d)
        rows.append(
            {
                "id": d.id,
                "title": d.title,
                "format": d.format,
                "path": f"final/{DELIVERABLES_DIR}/{d.filename}",
                "description": d.description,
                "sections": feeding,
                "missing": missing,
                "ready": not missing and bool(d.sections),
                "built_at": str(d.built_at) if d.built_at else None,
                "exists": path.exists(),
                "stale": stale,
            }
        )
    return rows


def for_section(spec: SpecState, section_id: str) -> list[dict[str, str]]:
    """Compact view of the deliverables a section feeds — what the drill loads."""
    return [
        {"id": d.id, "title": d.title, "format": d.format, "description": d.description}
        for d in spec.deliverables_for_section(section_id)
    ]


def plan(project: Project, deliverable_id: str | None = None) -> list[dict[str, Any]]:
    """Readiness plus the concrete inputs the finalize step reads: each feeding
    section's workfile slice location and the promoted shard (if any)."""
    spec = project.spec()
    rows = readiness(project, spec)
    if deliverable_id:
        rows = [r for r in rows if r["id"] == deliverable_id]
        if not rows:
            raise GreenhouseError(f"Unknown deliverable: {deliverable_id}")
    for row in rows:
        inputs = []
        for entry in row["sections"]:
            sec = spec.section_by_id(entry["section"])
            workfile = sec.workfile if sec else None
            shard = None
            if workfile:
                shard_name = workfile.partition("#")[0].rsplit("/", 1)[-1]
                if (project.final_dir / shard_name).exists():
                    shard = f"final/{shard_name}"
            inputs.append({**entry, "workfile": workfile, "shard": shard})
        row["inputs"] = inputs
    return rows


def write(
    project: Project,
    deliverable_id: str,
    content: str,
    allow_unready: bool = False,
) -> str:
    """Land the deliverable's file under final/deliverables/. Provenance and
    ref markers are stripped like a shard's; a leak of sources/ or
    history/references/ material aborts (never overridable). Refuses when a
    feeding section is not agreed/locked unless `allow_unready`. Stamps
    `built_at` and regenerates the folder's README index."""
    from . import bundle as bundle_mod  # local: bundle imports sources too

    spec = project.spec()
    d = spec.deliverable_by_id(deliverable_id)
    if d is None:
        raise GreenhouseError(f"Unknown deliverable: {deliverable_id}")
    row = next(r for r in readiness(project, spec) if r["id"] == d.id)
    if not row["ready"] and not allow_unready:
        why = (
            "no feeding sections declared"
            if not d.sections
            else "feeding sections not agreed/locked: " + ", ".join(row["missing"])
        )
        raise GreenhouseError(
            f"Deliverable {d.id!r} is not ready ({why}). "
            "Drill them first or pass --allow-unready (leaks are never overridable)."
        )
    if not content.strip():
        raise GreenhouseError(f"Refusing to write an empty deliverable {d.id!r}")

    cleaned = bundle_mod.strip_for_final(content).rstrip() + "\n"
    patterns = sources.leak_patterns(project)
    rel = f"final/{DELIVERABLES_DIR}/{d.filename}"
    for pattern in patterns:
        if pattern and pattern in cleaned:
            raise LeakError(
                f"Leak into {rel}: {pattern!r} found. Restate the fact on its own "
                "terms; internal material never ships."
            )
    path = target_path(project, d)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(cleaned)
    project.mark_deliverable_built(d.id)
    project.save()
    write_index(project)
    return rel


def write_index(project: Project) -> str | None:
    """Regenerate final/deliverables/README.md: what each file is, what it
    covers, when it was built. Returns the relative path, or None when the
    project declares no deliverables."""
    spec = project.spec()
    if not spec.deliverables:
        return None
    rows = readiness(project, spec)
    lines = [
        f"# Deliverables — {spec.title or project.name}",
        "",
        INDEX_HEADER,
        "",
        "| Deliverable | File | Format | Built | Status |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        if r["exists"]:
            status = "stale" if r["stale"] else "current"
        else:
            status = "ready to write" if r["ready"] else "not yet (spec incomplete)"
        link = f"[{r['path'].rsplit('/', 1)[-1]}]({r['path'].rsplit('/', 1)[-1]})"
        lines.append(
            f"| {r['title']} | {link if r['exists'] else r['path'].rsplit('/', 1)[-1]} "
            f"| {r['format']} | {r['built_at'] or '—'} | {status} |"
        )
    lines.append("")
    for r in rows:
        lines += [f"## {r['title']}", "", r["description"] or "_No description._", ""]
    content = "\n".join(lines)
    folder = project.final_dir / DELIVERABLES_DIR
    folder.mkdir(parents=True, exist_ok=True)
    (folder / INDEX_NAME).write_text(content)
    return f"final/{DELIVERABLES_DIR}/{INDEX_NAME}"
