"""sources/ — curated input material: indexed in spec-state,
checksummed for drift, citable while working, and barred from final/."""

from __future__ import annotations

import datetime as dt
import hashlib
import re
import shutil
from pathlib import Path
from typing import TYPE_CHECKING, Any

from ruamel.yaml.comments import CommentedMap

from . import mdutil
from .models import GreenhouseError
from .state import today

if TYPE_CHECKING:
    from .models import SpecState
    from .state import Project

_TEXT_SUFFIXES = {".md", ".txt", ".rst", ".csv", ".json", ".yaml", ".yml"}
_SHINGLE_WORDS = 12  # verbatim-run threshold for confidential sources


def sha256_of(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


# ---------------------------------------------------------------------------
# Registration
# ---------------------------------------------------------------------------


def add_source(
    project: Project,
    target: str,
    title: str,
    kind: str | None = None,
    relates_to: list[str] | None = None,
    confidential: bool = False,
    note: str | None = None,
    added_by: str = "user",
    date: dt.date | None = None,
) -> str:
    """Register a file (copied into sources/ if outside it) or a URL.
    Returns the src-NNNN id; sources/INDEX.md is regenerated."""
    spec = project.spec()
    date = date or today()
    relates_to = relates_to or []
    for rel in relates_to:
        if not spec.section_by_id(rel):
            raise GreenhouseError(f"relates_to section {rel!r} does not resolve")

    is_url = bool(re.match(r"https?://", target))
    kind = kind or ("url" if is_url else "file")

    src_id = project.next_source_id()
    entry = CommentedMap()
    entry["id"] = src_id
    entry["title"] = title
    entry["kind"] = kind
    if is_url:
        entry["path"] = None
        entry["url"] = target
        entry["checksum"] = None
    else:
        src_path = Path(target).expanduser()
        if not src_path.exists():
            raise GreenhouseError(f"No such file: {target}")
        project.sources_dir.mkdir(parents=True, exist_ok=True)
        dest = project.sources_dir / src_path.name
        if src_path.resolve() != dest.resolve():
            if dest.exists():
                raise GreenhouseError(f"sources/{dest.name} already exists")
            shutil.copy2(src_path, dest)
        entry["path"] = f"sources/{dest.name}"
        entry["url"] = None
        entry["checksum"] = sha256_of(dest)
    entry["added"] = date
    entry["added_by"] = added_by
    entry["relates_to"] = list(relates_to)
    entry["confidential"] = confidential
    entry["note"] = note
    project._raw_list("sources").append(entry)
    project.save()
    regenerate_index(project)
    return src_id


def regenerate_index(project: Project) -> None:
    spec = project.spec()
    lines = [f"# Sources — {project.name}", "", "<!-- generated by `greenhouse source` -->", ""]
    if not spec.sources:
        lines.append("_No sources registered yet. Add with `greenhouse source add`._")
    else:
        lines += ["| id | kind | title | where | relates to | flags |", "|---|---|---|---|---|---|"]
        for s in spec.sources:
            where = s.path or s.url or "—"
            flags = "confidential" if s.confidential else ""
            lines.append(
                f"| {s.id} | {s.kind} | {s.title} | {where} | "
                f"{', '.join(s.relates_to) or '—'} | {flags} |"
            )
    (project.sources_dir / "INDEX.md").write_text("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# Drift, citations, orphans
# ---------------------------------------------------------------------------


def check(project: Project) -> list[dict[str, Any]]:
    """Re-hash files; report drifted/missing sources (URLs are noted, not fetched)."""
    findings: list[dict[str, Any]] = []
    for s in project.spec().sources:
        if s.kind == "file" or s.path:
            path = project.root / (s.path or "")
            if not path.exists():
                findings.append({"source": s.id, "kind": "missing", "detail": s.path})
            elif s.checksum and sha256_of(path) != s.checksum:
                findings.append(
                    {"source": s.id, "kind": "drifted",
                     "detail": f"{s.path} changed since registration"}
                )
        elif s.url:
            findings.append(
                {"source": s.id, "kind": "unchecked-url",
                 "detail": f"{s.url} (verify manually or via the reference cache)"}
            )
    return findings


def citing_sections(project: Project, spec: SpecState, ident: str) -> set[str]:
    """Sections whose workfile slice (or whole file) cites `ident` in a ref marker."""
    citing_files: dict[str, set[int]] = {}
    if project.workfiles_dir.exists():
        for wf in sorted(project.workfiles_dir.glob("*.md")):
            lines = {ln for ln, rid in mdutil.extract_ref_ids(wf.read_text()) if rid == ident}
            if lines:
                citing_files[f"workfiles/{wf.name}"] = lines
    result: set[str] = set()
    for sec in spec.sections:
        if not sec.workfile:
            continue
        path, _, anchor = sec.workfile.partition("#")
        if path not in citing_files:
            continue
        if not anchor:
            result.add(sec.id)
            continue
        text = (project.root / path).read_text()
        sliced = mdutil.extract_section_slice(text, anchor)
        if sliced and any(ident in line for line in sliced.splitlines()):
            result.add(sec.id)
    return result


def drifted_citations(project: Project, spec: SpecState) -> list[dict[str, Any]]:
    """Stale entries for coverage: agreed sections leaning on a drifted source."""
    items: list[dict[str, Any]] = []
    drifted = [f["source"] for f in check(project) if f["kind"] in ("drifted", "missing")]
    for src_id in drifted:
        src = spec.source_by_id(src_id)
        affected = set(src.relates_to if src else []) | citing_sections(project, spec, src_id)
        for sid in sorted(affected):
            sec = spec.section_by_id(sid)
            if sec and sec.maturity in ("agreed", "locked"):
                items.append(
                    {"section": sec.id, "reason": "source-drifted", "source": src_id}
                )
    return items


def orphans(project: Project) -> dict[str, Any]:
    """Uncited sources, and citations pointing at unregistered/missing sources."""
    spec = project.spec()
    known = {s.id for s in spec.sources}
    cited: set[str] = set()
    dangling: list[dict[str, Any]] = []
    if project.workfiles_dir.exists():
        for wf in sorted(project.workfiles_dir.glob("*.md")):
            for lineno, rid in mdutil.extract_ref_ids(wf.read_text()):
                if not rid.startswith("src-"):
                    continue
                cited.add(rid)
                if rid not in known:
                    dangling.append(
                        {"file": f"workfiles/{wf.name}", "line": lineno + 1, "id": rid}
                    )
    return {"uncited": sorted(known - cited), "dangling": dangling}


# ---------------------------------------------------------------------------
# Confidential-verbatim guard (used by lint) + leak patterns (used by bundle)
# ---------------------------------------------------------------------------


def _shingles(text: str, n: int = _SHINGLE_WORDS) -> set[tuple[str, ...]]:
    words = re.findall(r"[\w'-]+", text.lower())
    return {tuple(words[i:i + n]) for i in range(max(0, len(words) - n + 1))}


def confidential_leaks(project: Project) -> list[dict[str, Any]]:
    """Workfile passages that quote a confidential text source verbatim
    (≥ {_SHINGLE_WORDS} consecutive words)."""
    spec = project.spec()
    findings: list[dict[str, Any]] = []
    conf_shingles: dict[str, set[tuple[str, ...]]] = {}
    for s in spec.sources:
        if s.confidential and s.path:
            path = project.root / s.path
            if path.exists() and path.suffix.lower() in _TEXT_SUFFIXES:
                conf_shingles[s.id] = _shingles(path.read_text())
    if not conf_shingles or not project.workfiles_dir.exists():
        return findings
    for wf in sorted(project.workfiles_dir.glob("*.md")):
        wf_shingles = _shingles(wf.read_text())
        for src_id, shingles in conf_shingles.items():
            if wf_shingles & shingles:
                findings.append(
                    {"file": f"workfiles/{wf.name}", "source": src_id,
                     "detail": f"verbatim run (≥{_SHINGLE_WORDS} words) from confidential {src_id}"}
                )
    return findings


def leak_patterns(project: Project) -> list[str]:
    """Strings that must never appear under final/: every src-/ref- id, the
    sources/ and history/references/ paths, and source file basenames."""
    spec = project.spec()
    patterns = ["sources/", "history/references/"]
    patterns += [s.id for s in spec.sources]
    patterns += [Path(s.path).name for s in spec.sources if s.path]
    from . import references as references_mod

    patterns += [r["id"] for r in references_mod.list_references(project)]
    return patterns
